name: Build Lua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Build Tools
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      
    - name: Build x86
      run: |
        make generic LUA_A=liblua.dll LUA_SO=
        cp liblua.dll ../../
      working-directory: ./build-lua/src
    
    - name: Build x86_64
      run: |
        make generic LUA_A=liblua_x86_64.dll LUA_SO=
        cp liblua_x86_64.dll ../../
      working-directory: ./build-lua/src
    
    - name: Build arm64
      run: |
        make generic LUA_A=liblua_arm64.so LUA_SO=
        cp liblua_arm64.so ../../
      working-directory: ./build-lua/src
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lua_build
        path: |
          liblua.dll
          liblua_x86_64.dll
          liblua_arm64.so
