name: Build Lua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Build Tools
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      
    - name: Build x86
      run: |
        make generic && mv liblua.a liblua_x86.a
        cp liblua_x86.a ../
      working-directory: ./build-lua/src
    
    - name: Build x86_64
      run: |
        make generic && mv liblua.a liblua_x86_64.a
        cp liblua_x86_64.a ../
      working-directory: ./build-lua/src
    
    - name: Build arm64
      run: |
        make generic && mv liblua.a liblua_arm64.a
        cp liblua_arm64.a ../
      working-directory: ./build-lua/src
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lua_build
        path: |
          liblua_x86.a
          liblua_x86_64.a
          liblua_ios.a
          liblua_android.so
          liblua_webgl.a
          liblua_arm64.a
